create table test_book (id number PRIMARY KEY , name nvarchar2(100), author nvarchar2(100), price number);

create table test_company (id int GENERATED BY DEFAULT ON NULL AS IDENTITY primary key, name NVARCHAR2(100), register_number nvarchar2(100), address nvarchar2(300), representative NVARCHAR2(100),
                           business_scope nvarchar2(400), capital nvarchar2(100),
                           phone nvarchar2(100), register_date NVARCHAR2(100), province NVARCHAR2(100)
)